# for testing backward compability
fields = ["plate", "frame_rate", "frame_in", "frame_out", "duration", "tc_in", "tc_out", "codec", "colorspace"]

[formats]
default = ["sequence", "frame_rate", "frame_in", "frame_out", "duration", "tc_in", "tc_out", "codec", "colorspace"]
plate = ["plate:sequence", "frame_rate", "in:frame_in", "out:frame_out"]


[seq]

[[seq.fields]]
name = "sequence"
value = "{{abspath (dirname $.FirstFile)}}"

[[seq.fields]]
name = "frame_in"
value = "{{$.Start}}"

[[seq.fields]]
name = "frame_out"
value = "{{$.End}}"

[[seq.fields]]
name = "duration"
value = "{{$.Length}}"

[[seq.fields]]
name = "tc_in"
value = """{{output "oiiotool" $.FirstFile "--echo" "{TOP.'smpte:Timecode'}"}}"""

[[seq.fields]]
name = "tc_out"
value = """{{output "oiiotool" $.LastFile "--echo" "{TOP.'smpte:Timecode'}"}}"""


[mov]

[[mov.fields]]
name = "sequence"
value = "{{abspath $.File}}"

[[mov.fields]]
name = "codec"
value = "{{$.Codec}}"

[[mov.fields]]
name = "colorspace"
value = "{{$.Colorspace}}"

[[mov.fields]]
name = "duration"
value = "{{$.Duration}}"

[[mov.fields]]
name = "frame_rate"
value = "{{$.FPS}}"

[[mov.fields]]
name = "tc_in"
value = "{{$.TimecodeIn}}"

[[mov.fields]]
name = "tc_out"
value = "{{$.TimecodeOut}}"
