fields = ["plate", "frame_in", "frame_out", "duration", "tc_in", "tc_out"]

[seq]

[[seq.fields]]
name = "plate"
value = "{{abspath (dirname $.FirstFile)}}"

[[seq.fields]]
name = "frame_in"
value = "{{$.Start}}"

[[seq.fields]]
name = "frame_out"
value = "{{$.End}}"

[[seq.fields]]
name = "duration"
value = "{{$.Length}}"

[[seq.fields]]
name = "tc_in"
value = """{{output "oiiotool" $.FirstFile "--echo" "{TOP.'smpte:Timecode'}"}}"""

[[seq.fields]]
name = "tc_out"
value = """{{output "oiiotool" $.LastFile "--echo" "{TOP.'smpte:Timecode'}"}}"""

[mov]

[[mov.fields]]
name = "plate"
value = "{{abspath $.File}}"

[[mov.fields]]
name = "duration"
value = """{{output "bin/movinfo" "-duration" $.File}}"""

[[mov.fields]]
name = "tc_in"
value = """{{output "bin/movinfo" "-start" $.File}}"""

[[mov.fields]]
name = "tc_out"
value = """{{output "bin/movinfo" "-end" $.File}}"""
