[[fields]]
name = "plate"
value = "{{abspath (dirname $.FirstFile)}}"

[[fields]]
name = "frame_in"
value = "{{$.Start}}"

[[fields]]
name = "frame_out"
value = "{{$.End}}"

[[fields]]
name = "tc_in"
value = """{{output "oiiotool" $.FirstFile "--echo" "{TOP.'smpte:Timecode'}"}}"""

[[fields]]
name = "tc_out"
value = """{{output "oiiotool" $.LastFile "--echo" "{TOP.'smpte:Timecode'}"}}"""
